import { Document } from './types';

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    title: 'Rencana Strategis (RENSTRA) 2024-2029',
    category: 'Renstra',
    type: 'PDF',
    year: 2024,
    dateAdded: '2024-02-10',
    size: '4.5 MB',
    description: 'Dokumen Rencana Strategis Dinas Ketahanan Pangan, Pertanian dan Perikanan Kota Cirebon periode 2024-2029.',
    coverColor: 'bg-emerald-600',
  },
  {
    id: 'doc-2',
    title: 'Rencana Kerja (RENJA) Tahun 2024',
    category: 'Renja',
    type: 'PDF',
    year: 2024,
    dateAdded: '2024-01-15',
    size: '3.2 MB',
    description: 'Dokumen Rencana Kerja tahunan untuk pelaksanaan program tahun 2024.',
    coverColor: 'bg-teal-600',
  },
  {
    id: 'doc-3',
    title: 'Laporan Akuntabilitas Kinerja (LAKIP) 2023',
    category: 'LAKIP/SAKIP',
    type: 'PDF',
    year: 2023,
    dateAdded: '2024-03-01',
    size: '5.8 MB',
    description: 'Laporan pertanggungjawaban kinerja instansi pemerintah DKPPP Kota Cirebon tahun 2023.',
    coverColor: 'bg-blue-600',
  },
  {
    id: 'doc-4',
    title: 'Laporan Evaluasi Renja DKPPP 2023',
    category: 'Evaluasi Renja',
    type: 'PDF',
    year: 2023,
    dateAdded: '2024-02-28',
    size: '8.1 MB',
    description: 'Laporan komprehensif evaluasi rencana kerja Dinas sepanjang tahun 2023.',
    coverColor: 'bg-indigo-600',
  },
  {
    id: 'doc-5',
    title: 'Rencana Kerja (RENJA) Tahun 2023',
    category: 'Renja',
    type: 'PDF',
    year: 2023,
    dateAdded: '2023-01-20',
    size: '3.0 MB',
    description: 'Dokumen Rencana Kerja tahunan untuk pelaksanaan program tahun 2023.',
    coverColor: 'bg-teal-600',
  },
  {
    id: 'doc-6',
    title: 'Laporan Interim Q4 2023',
    category: 'Laporan Interim',
    type: 'XLSX',
    year: 2023,
    dateAdded: '2024-01-10',
    size: '1.2 MB',
    description: 'Laporan interim realisasi anggaran kuartal keempat tahun 2023.',
    coverColor: 'bg-green-600',
  },
  {
    id: 'doc-7',
    title: 'Buku Profil Pertanian Kota Cirebon 2023',
    category: 'Lainnya',
    type: 'PDF',
    year: 2023,
    dateAdded: '2023-11-15',
    size: '12.4 MB',
    description: 'Publikasi data statistik dan profil pertanian wilayah Kota Cirebon.',
    coverColor: 'bg-orange-600',
  },
  {
    id: 'doc-8',
    title: 'Rencana Strategis (RENSTRA) 2019-2023',
    category: 'Renstra',
    type: 'PDF',
    year: 2019,
    dateAdded: '2019-02-10',
    size: '4.1 MB',
    description: 'Dokumen Rencana Strategis periode sebelumnya (2019-2023).',
    coverColor: 'bg-emerald-700',
  },
  {
    id: 'doc-9',
    title: 'Review SAKIP 2022',
    category: 'LAKIP/SAKIP',
    type: 'DOCX',
    year: 2022,
    dateAdded: '2023-04-05',
    size: '2.5 MB',
    description: 'Dokumen tinjauan dan evaluasi Sistem Akuntabilitas Kinerja Instansi Pemerintah tahun 2022.',
    coverColor: 'bg-blue-700',
  }
];
